### ISSUE TITLE
Issue: Server Unable to Process Base64 Encoded File Content in Leave Request

### ISSUE THREAD

**Issue by hemanth-sunkireddy** [IMS-IIITH/frontend#12]
In the apply leave request feature, we are currently sending a base64 encoded string. While the server successfully processes a base64 string of "Hello world" and returns a 200 response, it fails to process the actual base64 content of a file. This results in the server being unable to process the request. 

![Screenshot from 2024-05-26 12-00-01](https://github.com/IMS-IIITH/frontend/assets/117459441/8bf4ad6d-b404-48e7-b18f-b6b75951c6cf)

**Comment by bhavberi** [comment]
Fixed in https://github.com/IMS-IIITH/backend/commit/e91a76b22c0ee5cedc7dd2f857798f89eb0f1761
