### ISSUE TITLE
Sidebar: getting stuck after you return back

### ISSUE THREAD

**Issue by hemanth-sunkireddy** [IMS-IIITH/frontend#125]
## Problem
Currently unable to replicate in all devices. But observed in two such devices.

Steps to reproduce:
- Use the sidebar to go to any of the pages say 'Bank Details'. 
- Now use the back button to go back to dashboard.
- The sidebar is stuck on open. Now click on side buttons or swiping doesn't close the sidebar.
  Now only way out is to somehow click on the about page button.

https://github.com/user-attachments/assets/0c4615fe-ccd4-48fe-9b33-8f7c5dd530a8

**Comment by bhavberi** [comment]
Related: https://github.com/react-navigation/react-navigation/issues/11616#issuecomment-2136277382

**Comment by hemanth-sunkireddy** [comment]
8292c69b2bd22e633da285b940f4020c3af62825   Fixed
