### ISSUE TITLE
New/Update: Credits Page

### ISSUE THREAD

**Issue by bhavberi** [IMS-IIITH/frontend#16]
Add a credits page with the link to the organisation, as well as the names of the initial developers. 

You can update the same on the `About` page as well. 
Add that this project was started as a `DASS Project` in `Spring 2024`, under the guidance of `Prof. Raghu Reddy` and was further developed by the team along with the institute webadmins team.

Formatting, styling and other text - you can take care of.

**Comment by hemanth-sunkireddy** [comment]
#22 and #24 solved
