### ISSUE TITLE
Clearing Welcome Screen Error/Success Text

### ISSUE THREAD

**Issue by bhavberi** [IMS-IIITH/frontend#58]
Steps to reproduce:
1. Open the app when you are already logged in.
2. It would show the success text of redirecting to the dashboard.
3. Now from dashboard logout, and click Yes
4. You'll reach back on the welcome screen, where the `Step 2` successText will already be there, although it shouldn't be there.

**Comment by hemanth-sunkireddy** [comment]
#65 solved
